# Generated by Django 4.2.4 on 2023-11-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('Jednoduchá', 'Jednoduchá'), ('Střední', 'Medium'), ('Težká', 'Hard')], max_length=10),
        ),
    ]
