# Generated by Django 4.2.5 on 2024-02-02 20:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='users_favorited',
            field=models.ManyToManyField(related_name='favorited_recipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
