# Generated by Django 4.2.4 on 2023-11-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_recipe_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('Jednoduchá', 'Jednoduchá'), ('Střední', 'Střední'), ('Težká', 'Těžká')], max_length=10),
        ),
    ]
